### ISSUE TITLE
How can I build user_factors.csv and item_factors.csv

### ISSUE THREAD

**Issue by dmalagarriga** [evison/KBE4ExplainableRecommendation#1]
Hi, 
I'm trying to reproduce the results from your paper but I'm getting stuck when using Cell Phones dataset, as I am missing user and item factors. Besides, the explain_results.py file in the explain mode doesn't seem to explain the recommendation but only the many relationships a user or an item can have in terms of purchase, also_bought, etc. How is the training performed and how can I retrieve the information about the recommendation from the output_embeddings?

Thank you very much!

**Comment by QingyaoAi** [comment]
You can find the user and item factor data in the link below:
https://www.dropbox.com/sh/tcqs8250ohnguma/AAC19tDI3XAy4233BkKXveYWa?dl=0

Right now, we don't have a good interface for explaining the recommendation results. The explain_results.py only computes the score between items, users, and the corresponding relationships. You may need to manually compute the explanations based on them. We are currently working on a new version of the code and will provide better API in the future.

**Comment by dmalagarriga** [comment]
Hi again,

I am interested on reproducing the explanation path covered in your article for user A1P27BGF8NAI29 and item B9C in the Cell Phones domain.  So far I couldn’t do it even with the item-user factors I downloaded from your Dropbox repo. I have selected the line number for the user (14696) but the list I obtain from explain_results.py is the following (for rank 5):

Read model

Use all relation

L2 lambda 0.0

Created model with fresh parameters.

Start Interactive Process

Enter rank cut:

5

Enter mode, "product" for gathering product information and "user" for gathering user information:

user

Enter user idx (line number start from 0) or name (user id):

14696

User 14696 b'A1P27BGF8NAI29'

purchase list: rank, id, name, score

0              753         "b'B00E24KTYM'"             0.0002

1              7110       "b'B00AO00TB6'"              0.0002

2              2974       "b'B004I53B4A'"                0.0002

3              6936       "b'B004AJ718Q'"               0.0002

4              7258       "b'B009GOC0C2'"             0.0002

write list: rank, id, name, score

0              17930    "b'pieces'"          0.0002

1              21812    "b'stich'"              0.0002

2              14746    "b'shortthe'"      0.0002

3              14700    "b'pacman'"       0.0001

4              13876    "b'ericcson'"       0.0001

also_bought list: rank, id, name, score

0              29247    "b'B00DM8L056'"             0.0002

1              46224    "b'B006LPBBBK'"              0.0002

2              8052       "b'B000J2KLJY'" 0.0002

3              40298    "b'B003F6N88M'"             0.0002

4              16264    "b'B002YEL608'"                0.0002

also_viewed list: rank, id, name, score

0              11839    "b'B0047QQ9DK'"             0.0002

1              99003    "b'B00K5E7HES'"               0.0002

2              80170    "b'B00JBBYTCY'"               0.0002

3              13846    "b'B002G9P2WO'"           0.0002

4              31279    "b'B004HPZIHE'"               0.0002

bought_together list: rank, id, name, score

0              40298    "b'B003F6N88M'"             0.0003

1              22895    "b'B005XM6QYE'"            0.0002

2              87669    "b'B00AYA73YC'"              0.0002

3              2258       "b'B00J42D1UQ'"              0.0002

4              34215    "b'B00BH7C0TO'"             0.0002

brand list: rank, id, name, score

0              605         "b'Encased'"       0.0002

1              927         "b'Monoy&reg;'"             0.0002

2              739         "b'Focal3C'"        0.0001

3              284         "b'Case2'"           0.0001

4              903         "b'Toddy Gear'" 0.0001

categories list: rank, id, name, score

0              133         "b'PC Microphones'"      0.0001

1              138         "b'Stands'"          0.0001

2              114         "b'Hunting'"       0.0001

3              22           "b'Tool Sets'"     0.0001

4              89           "b'Mobile Hotspots'"      0.0001


There is no reference to item B9C. Could you please tell me about the full process for reproducing the results? I’m also getting stuck with a function called “get_product_scores” for the training process. I would really appreciate a bit more help to understand how your implementation works as it is really interesting.

Best,

--
Daniel Malagarriga Guasch, PhD
AI Research Scientist
Alpha Health AI Lab | Telefónica Innovación Alpha

E: daniel.malagarriga@telefonica.com
M: (+34) 676 27 42 58

[signature_524450825]
